### PR TITLE
Use to script on github to avoid it breaking on docs.

### PR DESCRIPTION
**Pull request by garloff**
Fixes issue #9 or so I hope at least.

### CODE REVIEW

**Comment by garloff** [comment]
So the commented out `relative-link-path` test in `.markdownlint-cli2.jsonc` did help to survive the markdownlint checks here, but these docs are pulled in from the docs page build and we still have the test there.
As the helper script is not copied over in the docs page build (unless we specifically ask docusaurus to do so), the link would not work either.
I assume it's best to link directly to github. Do this and switch own markdownlint test again.
With this, I expect the docs page build to get green again.

**Comment by garloff** [comment]
Sidenote: I'm surprised this repo does not require an approving review for merging into main. Is this intentional?

**Comment by tbreiden** [comment]
@garloff Thanks for the hint.

**Comment by fkr** [comment]
> Sidenote: I'm surprised this repo does not require an approving review for merging into main. Is this intentional?

that is because github-manager is not running properly and apparently this repo was also never really added to it properly. I'll look at that.

**Comment by fkr** [comment]
> Sidenote: I'm surprised this repo does not require an approving review for merging into main. Is this intentional?

I've fixed github-manager yesterday and as such this repo should now be properly managed as well by github-manager.

**Pull request merged**
